apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "erp-backend.fullname" . }}-config
  labels:
    {{- include "erp-backend.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.env.ASPNETCORE_ENVIRONMENT | quote }}
  ASPNETCORE_URLS: {{ .Values.env.ASPNETCORE_URLS | quote }}
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: {{ .Values.env.DOTNET_SYSTEM_GLOBALIZATION_INVARIANT | quote }}
  Finance__FeeReceivableAccountCode: {{ .Values.secrets.finance.feeReceivableAccountCode | quote }}
  Finance__CashAccountCode: {{ .Values.secrets.finance.cashAccountCode | quote }}
  Hangfire__DashboardPath: {{ .Values.secrets.hangfire.dashboardPath | quote }}
